# Generated by Django 3.0.5 on 2020-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('skills', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('leader', models.CharField(max_length=100)),
                ('members', models.TextField()),
                ('mem_needed', models.IntegerField()),
                ('applied', models.TextField()),
                ('min_payment', models.CharField(max_length=50)),
                ('max_payment', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('experience', models.CharField(max_length=254)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
    ]
