# Generated by Django 3.0.5 on 2021-02-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerapp', '0003_auto_20200417_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='ptype',
            field=models.CharField(default='search', max_length=100),
        ),
    ]
